parameters:
  site.parameters:
    name: 'My website name'
    locale: fr
    profile: standard
    language:
      uuid: ''
      locale: fr
    admin.account:
      name: admin
      password: admin
      mail: your@mail.fr
  dev.modules:
    - devel
    - kint
    - admin_toolbar
